version: '3.9'

services:

  nginx:
    image: nginx:1.25.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static
    depends_on:
      - app

  app:
    build: .
    command: gunicorn ssbwproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - ./datos_db:/data/db
